export const careerDatabase = [
  {
    id: "software-developer",
    title: "Software Developer",
    category: "Technology",
    description:
      "Design, develop, and maintain software applications and systems using programming languages and development tools.",
    suitableTypes: ["INTJ", "INTP", "ENTJ", "ENTP"],
    goodFitTypes: ["ISTJ", "ISTP", "INFJ", "INFP"],
    skills: ["Problem-solving", "Logical thinking", "Programming", "Attention to detail", "Creativity"],
    education: "Bachelor's degree in Computer Science or related field",
    salary: "$70,000 - $150,000",
    growthPotential: "High",
    workEnvironment: "Office, remote work, collaborative teams",
    personalityTraits: ["Analytical thinking", "Patience", "Curiosity", "Independence", "Adaptability"],
    challenges: [
      "Keeping up with rapidly changing technologies",
      "Debugging complex issues",
      "Meeting tight deadlines",
      "Balancing technical debt with new features",
    ],
    dayToDay: [
      "Writing and reviewing code",
      "Collaborating with team members",
      "Testing and debugging",
      "Participating in planning meetings",
      "Learning new technologies",
    ],
  },
  {
    id: "data-scientist",
    title: "Data Scientist",
    category: "Technology",
    description:
      "Analyze complex data sets to identify patterns, develop models, and provide insights that drive business decisions.",
    suitableTypes: ["INTJ", "INTP", "ENTJ", "ISTJ"],
    goodFitTypes: ["INFJ", "ENTP", "ISTP", "ESTJ"],
    skills: ["Statistical analysis", "Machine learning", "Programming", "Data visualization", "Critical thinking"],
    education: "Master's or PhD in Statistics, Computer Science, or related field",
    salary: "$90,000 - $160,000",
    growthPotential: "High",
    workEnvironment: "Office, research labs, collaborative teams",
    personalityTraits: [
      "Analytical thinking",
      "Curiosity",
      "Attention to detail",
      "Persistence",
      "Communication skills",
    ],
    challenges: [
      "Working with messy, incomplete data",
      "Explaining complex findings to non-technical stakeholders",
      "Balancing accuracy with business needs",
      "Keeping up with evolving methodologies",
    ],
    dayToDay: [
      "Cleaning and preprocessing data",
      "Building statistical models",
      "Creating visualizations",
      "Presenting findings to stakeholders",
      "Researching new techniques",
    ],
  },
  {
    id: "marketing-manager",
    title: "Marketing Manager",
    category: "Marketing",
    description: "Develop and implement marketing strategies to promote products, services, and brand awareness.",
    suitableTypes: ["ENFJ", "ENTJ", "ENFP", "ESFJ"],
    goodFitTypes: ["ENTP", "ESTJ", "ESFP", "INFJ"],
    skills: ["Strategic thinking", "Creativity", "Communication", "Project management", "Analytics"],
    education: "Bachelor's degree in Marketing, Business, or related field",
    salary: "$60,000 - $140,000",
    growthPotential: "Medium to High",
    workEnvironment: "Office, collaborative teams, client meetings",
    personalityTraits: ["Creativity", "Adaptability", "People skills", "Strategic thinking", "Persuasiveness"],
    challenges: [
      "Keeping up with changing consumer trends",
      "Measuring ROI of marketing efforts",
      "Managing multiple campaigns simultaneously",
      "Balancing creativity with business objectives",
    ],
    dayToDay: [
      "Developing marketing strategies",
      "Overseeing campaign execution",
      "Analyzing performance metrics",
      "Collaborating with creative teams",
      "Presenting to stakeholders",
    ],
  },
  {
    id: "clinical-psychologist",
    title: "Clinical Psychologist",
    category: "Healthcare",
    description:
      "Assess, diagnose, and treat mental, emotional, and behavioral disorders using various therapeutic techniques.",
    suitableTypes: ["INFJ", "ENFJ", "INFP", "ISFJ"],
    goodFitTypes: ["ENFP", "INTJ", "ISFP", "ESFJ"],
    skills: ["Empathy", "Active listening", "Analysis", "Patience", "Communication"],
    education: "Doctoral degree in Psychology, state licensure",
    salary: "$70,000 - $130,000",
    growthPotential: "Medium",
    workEnvironment: "Private practice, hospitals, clinics, schools",
    personalityTraits: ["Empathy", "Patience", "Emotional stability", "Analytical thinking", "Trustworthiness"],
    challenges: [
      "Maintaining professional boundaries",
      "Preventing burnout from emotional demands",
      "Keeping up with research and methodologies",
      "Managing administrative aspects of practice",
    ],
    dayToDay: [
      "Conducting therapy sessions",
      "Performing psychological assessments",
      "Developing treatment plans",
      "Maintaining client records",
      "Consulting with other healthcare providers",
    ],
  },
  {
    id: "financial-analyst",
    title: "Financial Analyst",
    category: "Finance",
    description:
      "Analyze financial data, prepare reports, and make recommendations to guide investment decisions and business strategy.",
    suitableTypes: ["ISTJ", "ESTJ", "INTJ", "ENTJ"],
    goodFitTypes: ["INTP", "ISTP", "ENTP", "ISFJ"],
    skills: ["Analytical thinking", "Attention to detail", "Financial modeling", "Research", "Communication"],
    education: "Bachelor's degree in Finance, Accounting, Economics, or related field",
    salary: "$60,000 - $120,000",
    growthPotential: "Medium to High",
    workEnvironment: "Office, financial institutions, consulting firms",
    personalityTraits: ["Analytical thinking", "Attention to detail", "Objectivity", "Persistence", "Ethical judgment"],
    challenges: [
      "Working under pressure during financial reporting periods",
      "Staying current with changing regulations",
      "Making accurate forecasts with limited information",
      "Communicating complex financial concepts to non-experts",
    ],
    dayToDay: [
      "Analyzing financial statements",
      "Building financial models",
      "Researching market trends",
      "Preparing reports and presentations",
      "Meeting with stakeholders",
    ],
  },
  {
    id: "graphic-designer",
    title: "Graphic Designer",
    category: "Creative",
    description:
      "Create visual concepts using computer software or by hand to communicate ideas that inspire, inform, or captivate consumers.",
    suitableTypes: ["ISFP", "INFP", "ENFP", "ISTP"],
    goodFitTypes: ["ESFP", "INTP", "ENTP", "INFJ"],
    skills: ["Creativity", "Visual thinking", "Design software", "Typography", "Communication"],
    education: "Bachelor's degree in Graphic Design or related field",
    salary: "$45,000 - $85,000",
    growthPotential: "Medium",
    workEnvironment: "Design studios, agencies, in-house creative departments, freelance",
    personalityTraits: ["Creativity", "Attention to detail", "Adaptability", "Patience", "Visual thinking"],
    challenges: [
      "Meeting tight deadlines",
      "Balancing client expectations with creative vision",
      "Staying current with design trends and software",
      "Receiving and implementing feedback",
    ],
    dayToDay: [
      "Creating design concepts",
      "Working with design software",
      "Collaborating with clients and team members",
      "Revising designs based on feedback",
      "Preparing files for production",
    ],
  },
  {
    id: "teacher",
    title: "Teacher",
    category: "Education",
    description:
      "Educate students in various subjects, develop lesson plans, assess progress, and create a positive learning environment.",
    suitableTypes: ["ENFJ", "ESFJ", "INFJ", "ISFJ"],
    goodFitTypes: ["ENFP", "ENTJ", "INFP", "ISTJ"],
    skills: ["Communication", "Patience", "Organization", "Adaptability", "Empathy"],
    education: "Bachelor's degree in Education or subject area, teaching certification",
    salary: "$40,000 - $85,000",
    growthPotential: "Medium",
    workEnvironment: "Schools, educational institutions, online platforms",
    personalityTraits: ["Patience", "Empathy", "Enthusiasm", "Adaptability", "Organization"],
    challenges: [
      "Managing diverse learning needs",
      "Balancing administrative tasks with teaching",
      "Staying energized throughout the day",
      "Adapting to changing educational policies",
    ],
    dayToDay: [
      "Preparing and delivering lessons",
      "Assessing student progress",
      "Managing classroom behavior",
      "Communicating with parents and colleagues",
      "Continuing professional development",
    ],
  },
  {
    id: "nurse",
    title: "Nurse",
    category: "Healthcare",
    description:
      "Provide and coordinate patient care, educate patients about health conditions, and provide advice and emotional support.",
    suitableTypes: ["ISFJ", "ESFJ", "ENFJ", "ISFP"],
    goodFitTypes: ["ISTJ", "ENFP", "INFJ", "ESFP"],
    skills: ["Empathy", "Communication", "Critical thinking", "Attention to detail", "Stamina"],
    education: "Associate's or Bachelor's degree in Nursing, state licensure",
    salary: "$60,000 - $110,000",
    growthPotential: "High",
    workEnvironment: "Hospitals, clinics, nursing homes, schools, home healthcare",
    personalityTraits: ["Compassion", "Resilience", "Attention to detail", "Adaptability", "Emotional stability"],
    challenges: [
      "Working long shifts, often on feet",
      "Handling emotionally challenging situations",
      "Managing multiple patients with diverse needs",
      "Staying current with medical knowledge and procedures",
    ],
    dayToDay: [
      "Assessing patient conditions",
      "Administering treatments and medications",
      "Coordinating with healthcare team",
      "Educating patients and families",
      "Maintaining medical records",
    ],
  },
  {
    id: "human-resources-manager",
    title: "Human Resources Manager",
    category: "Business",
    description:
      "Oversee recruitment, employee relations, benefits administration, and ensure compliance with labor laws and regulations.",
    suitableTypes: ["ENFJ", "ESFJ", "ENTJ", "ESTJ"],
    goodFitTypes: ["INFJ", "ISFJ", "ENFP", "ISTJ"],
    skills: ["People management", "Communication", "Organization", "Conflict resolution", "Discretion"],
    education: "Bachelor's degree in Human Resources, Business, or related field",
    salary: "$65,000 - $130,000",
    growthPotential: "Medium to High",
    workEnvironment: "Corporate offices, HR departments across industries",
    personalityTraits: ["Diplomacy", "Fairness", "Discretion", "Organization", "Empathy"],
    challenges: [
      "Balancing employee advocacy with business needs",
      "Handling sensitive personnel issues",
      "Staying current with changing employment laws",
      "Managing organizational change",
    ],
    dayToDay: [
      "Recruiting and interviewing candidates",
      "Addressing employee relations issues",
      "Developing HR policies and procedures",
      "Managing benefits and compensation",
      "Conducting training and development programs",
    ],
  },
  {
    id: "entrepreneur",
    title: "Entrepreneur",
    category: "Business",
    description:
      "Start and run businesses, identify opportunities, secure funding, develop products or services, and build teams.",
    suitableTypes: ["ENTJ", "ENTP", "ESTP", "INTJ"],
    goodFitTypes: ["ENFJ", "ESTJ", "ISTP", "ENFP"],
    skills: ["Risk-taking", "Leadership", "Creativity", "Resilience", "Strategic thinking"],
    education: "Varies widely - from no formal education to advanced degrees",
    salary: "Highly variable - from negative to millions",
    growthPotential: "Unlimited but high risk",
    workEnvironment: "Self-created, startups, small businesses, home offices",
    personalityTraits: ["Risk tolerance", "Self-motivation", "Adaptability", "Persistence", "Vision"],
    challenges: [
      "Financial uncertainty and risk",
      "Work-life balance challenges",
      "Wearing multiple hats, especially early on",
      "Handling failure and setbacks",
      "Scaling operations effectively",
    ],
    dayToDay: [
      "Strategic planning and decision making",
      "Meeting with investors or clients",
      "Product or service development",
      "Team building and leadership",
      "Problem-solving and crisis management",
    ],
  },
  {
    id: "social-worker",
    title: "Social Worker",
    category: "Social Services",
    description:
      "Help people solve and cope with problems in their everyday lives, connect clients with resources, and advocate for community support.",
    suitableTypes: ["INFJ", "ENFJ", "ISFJ", "ESFJ"],
    goodFitTypes: ["INFP", "ENFP", "ISFP", "ISTJ"],
    skills: ["Empathy", "Communication", "Problem-solving", "Cultural competence", "Emotional resilience"],
    education: "Bachelor's or Master's degree in Social Work, state licensure",
    salary: "$45,000 - $75,000",
    growthPotential: "Medium",
    workEnvironment: "Government agencies, hospitals, schools, non-profit organizations",
    personalityTraits: ["Compassion", "Patience", "Resilience", "Advocacy", "Boundary-setting"],
    challenges: [
      "Emotional toll of working with people in crisis",
      "Large caseloads and administrative burden",
      "Limited resources to help clients",
      "Witnessing systemic inequities",
      "Maintaining professional boundaries",
    ],
    dayToDay: [
      "Conducting client assessments",
      "Developing intervention plans",
      "Connecting clients with resources",
      "Documenting case notes",
      "Advocating for clients' needs",
    ],
  },
  {
    id: "architect",
    title: "Architect",
    category: "Design",
    description:
      "Design buildings and structures, prepare construction documents, and oversee projects from conception to completion.",
    suitableTypes: ["INTJ", "INTP", "ISTP", "ENTJ"],
    goodFitTypes: ["INFJ", "ISTJ", "ENTP", "ISFP"],
    skills: ["Spatial thinking", "Creativity", "Technical drawing", "Problem-solving", "Communication"],
    education: "Bachelor's or Master's degree in Architecture, professional licensure",
    salary: "$70,000 - $130,000",
    growthPotential: "Medium",
    workEnvironment: "Architecture firms, construction companies, government agencies",
    personalityTraits: [
      "Attention to detail",
      "Creativity",
      "Patience",
      "Analytical thinking",
      "Visual-spatial awareness",
    ],
    challenges: [
      "Balancing creative vision with practical constraints",
      "Meeting strict deadlines and budgets",
      "Navigating building codes and regulations",
      "Coordinating with various stakeholders",
      "Keeping up with new materials and technologies",
    ],
    dayToDay: [
      "Creating design concepts and drawings",
      "Using CAD and modeling software",
      "Meeting with clients and contractors",
      "Visiting construction sites",
      "Preparing technical documents",
    ],
  },
]
